Fix daemon's service autostart after instalation from package
Signed-off-by: Roman Ondráček <ondracek.roman@centrum.cz>

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -34,3 +34,19 @@ remove_old_dirs() {
 if [ "$1" = "configure" ]; then
     remove_old_dirs
 fi
+
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# This will only remove masks created by d-s-h on package removal.
+	deb-systemd-helper unmask iqrf-gateway-daemon.service >/dev/null || true
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled iqrf-gateway-daemon.service; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable iqrf-gateway-daemon.service >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state iqrf-gateway-daemon.service >/dev/null || true
+	fi
+	deb-systemd-invoke start iqrf-gateway-daemon.service >/dev/null || true
+fi
